CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	middle_initial VARCHAR(2) NOT NULL,
	suffix VARCHAR(10) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	role ENUM('ADMIN', 'FACULTY', 'STUDENT') NOT NULL,
	user_id INT NOT NULL,
	UNIQUE (role, user_id),

	CONSTRAINT fk_roles_users
		FOREIGN KEY (user_id)
		REFERENCES users(id)
);
